'use strict';
/* Presentation-only shell: existing editing, save and export handlers remain the source of truth. */
const artPaths={back:'M15 5l-7 7 7 7',text:'M4 5h16M12 5v15M8 20h8',image:'M4 4h16v16H4zM4 16l5-5 4 4 3-3 4 4M8 8h.01',shapes:'M3 4h8v8H3zM17 3l4 8h-8zM12 18a4 4 0 1 0 8 0 4 4 0 0 0-8 0',print:'M6 9V3h12v6M6 17H3V9h18v8h-3M6 14h12v7H6zM17 11h.01',export:'M12 15V3M8 7l4-4 4 4M4 13v7h16v-7',undo:'M8 5L3 10l5 5M3 10h11a6 6 0 0 1 6 6',redo:'M16 5l5 5-5 5M21 10H10a6 6 0 0 0-6 6',layers:'M12 3L2 8l10 5 10-5-10-5M2 12l10 5 10-5M2 16l10 5 10-5',properties:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M9 15v6',close:'M6 6l12 12M18 6L6 18',copy:'M8 8h13v13H8zM16 8V3H3v13h5',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',group:'M3 3h7v7H3zM14 14h7v7h-7zM14 3h7v7h-7zM3 14h7v7H3z',lock:'M6 11h12v10H6zM8 11V7a4 4 0 0 1 8 0v4M12 15v2',crop:'M6 2v16h16M2 6h16v16',up:'M12 20V4M6 10l6-6 6 6',down:'M12 4v16M6 14l6 6 6-6',file:'M5 3h10l4 4v14H5zM15 3v5h4',cloud:'M7 18a5 5 0 1 1 1-10 5 5 0 0 1 9 1 4 4 0 1 1 1 9z',plus:'M12 4v16M4 12h16',theme:'M12 3v18M3 12h18M6 6l12 12M18 6L6 18',align:'M4 4v16M7 6h12M7 12h8M7 18h12'};
function artIcon(name){return '<svg class="artIcon" viewBox="0 0 24 24" aria-hidden="true"><path d="'+(artPaths[name]||artPaths.properties)+'"/></svg>'}
const artMark='<svg class="artMark" viewBox="0 0 64 64" aria-hidden="true"><rect x="4" y="4" width="56" height="56" rx="12" fill="#B92C3B"/><path d="M18 13h21l9 9v27H18z" fill="#fff"/><path d="M39 13v10h9" fill="none" stroke="#B92C3B" stroke-width="2"/><path d="M24 28h15M24 34h11" fill="none" stroke="#B92C3B" stroke-width="3"/><circle cx="45" cy="45" r="11" fill="#D9AD46"/><path d="M40 45l3 3 6-7" fill="none" stroke="#25262B" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>';
function artDecorate(button,name,label=null){if(!button)return;const accessible=button.getAttribute('aria-label')||button.textContent.trim().replace(/\s+/g,' ');button.setAttribute('aria-label',accessible);button.classList.add('artButton');button.innerHTML=artIcon(name)+(label===null?'': '<span>'+label+'</span>');button.classList.toggle('artIconButton',label===null);if(!button.title)button.title=accessible}
function artButton(id,label,icon,action){const button=document.createElement('button');button.type='button';button.id=id;button.textContent=label;artDecorate(button,icon,null);button.onclick=action;return button}
const artHeader=document.querySelector('.wordTitle'),artQuick=document.querySelector('.quickActions'),artIdentity=document.createElement('div');artIdentity.className='artIdentity';artIdentity.innerHTML=artMark+'<div><strong>TEMhoa</strong><small>Minh Điến · Thiết kế & in</small></div>';
const artOldIdentity=artHeader.firstElementChild;artHeader.prepend(homeBack,artIdentity);artOldIdentity.remove();artDecorate(homeBack,'back',null);
const artMain=document.createElement('div');artMain.className='artMainTools';artHeader.insertBefore(artMain,artQuick);
for(const [id,icon,label] of [['designAddText','text','Văn bản'],['designAddImage','image','Ảnh'],['insertGraphics','shapes','Thành phần']]){artMain.append($(id));artDecorate($(id),icon,label)}
const artUndo=artButton('artUndo','Hoàn tác','undo',()=>restoreHistory(-1)),artRedo=artButton('artRedo','Làm lại','redo',()=>restoreHistory(1));artMain.prepend(artUndo,artRedo);
const artPropButton=artButton('artPropertiesButton','Thuộc tính','properties',()=>artOpenPanel('properties'));artQuick.prepend(artPropButton,toggleLayers);artDecorate(toggleLayers,'layers',null);artDecorate($('print'),'print','In');
const artExport=artButton('artExportButton','Xuất file','export',()=>artToggleExport());artDecorate(artExport,'export','Xuất');artExport.setAttribute('aria-label','Mở menu xuất file');artExport.title='Mở menu xuất file';artExport.setAttribute('aria-haspopup','menu');artExport.setAttribute('aria-expanded','false');artQuick.append(artExport);
const artExportMenu=document.createElement('div');artExportMenu.id='artExportMenu';artExportMenu.hidden=true;artExportMenu.setAttribute('role','menu');artExportMenu.setAttribute('aria-label','Xuất và mở thiết kế');document.body.append(artExportMenu);
for(const id of ['png','svg','word','load']){const button=$(id);artExportMenu.append(button);button.setAttribute('role','menuitem');button.addEventListener('click',()=>artCloseExport())}
normalTemplatesButton.hidden=true;saveAsButton.hidden=true;
function artCloseExport(restore=false){artExportMenu.hidden=true;artExport.setAttribute('aria-expanded','false');if(restore)artExport.focus()}
function artToggleExport(){if(!artExportMenu.hidden){artCloseExport(true);return}const rect=artExport.getBoundingClientRect();artExportMenu.style.left=Math.max(8,Math.min(innerWidth-228,rect.right-220))+'px';artExportMenu.style.top=(rect.bottom+7)+'px';artExportMenu.hidden=false;artExport.setAttribute('aria-expanded','true');artExportMenu.querySelector('button').focus()}
document.addEventListener('pointerdown',event=>{if(!artExportMenu.contains(event.target)&&!artExport.contains(event.target))artCloseExport()});
artExportMenu.onkeydown=event=>{const items=[...artExportMenu.querySelectorAll('button:not(:disabled)')],index=items.indexOf(document.activeElement);if(event.key==='Escape'){event.preventDefault();artCloseExport(true)}else if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus()}};
/* Reparent original controls, preserving listeners, values and formatting selections. */
const artRibbon=$('homeRibbon'),artFontGroup=document.querySelector('.fontGroup'),artFontRow=artFontGroup.firstElementChild,artParagraph=paragraphGroup;
const artTextZone=document.createElement('div');artTextZone.className='artContextZone';artTextZone.id='artTextZone';artRibbon.append(artTextZone);
const artContextLabel=document.createElement('span');artContextLabel.id='artContextLabel';artContextLabel.textContent='Chữ';artTextZone.append(artContextLabel,artFontRow);
const artTextStyles=document.createElement('div');artTextStyles.className='ribbonRow';artTextZone.append(artTextStyles);for(const id of ['bold','italic','underline'])artTextStyles.append($(id).closest('label'));artTextStyles.append($('caseButton').closest('.casePicker'),document.querySelector('.alignTools'),$('paint-fill'));
const artImageZone=document.createElement('div');artImageZone.className='artContextZone';artImageZone.id='artImageZone';artImageZone.hidden=true;artRibbon.append(artImageZone);
for(const [id,label,icon,target]of [['artImageProperties','Ảnh đang chọn','properties',null],['artImageCrop','Cắt ảnh','crop','startGraphicCrop'],['artImageBackground','Tách nền','image','openBackgroundAI']]){const button=artButton(id,label,icon,()=>{graphicsDialog.show();if(target)$(target).click()});artDecorate(button,icon,label==='Ảnh đang chọn'?'Ảnh đang chọn':label);artImageZone.append(button)}
artImageZone.append($('quickImageLock'));artDecorate($('quickImageLock'),'lock','Khóa');
const artSelectionTools=document.createElement('div');artSelectionTools.id='artSelectionTools';artRibbon.append(artSelectionTools);for(const id of ['groupGraphics','ungroupGraphics','layerUp','layerDown','designEditText','designFinishText','designDuplicate','designDelete']){artSelectionTools.append($(id));const icon={groupGraphics:'group',ungroupGraphics:'group',layerUp:'up',layerDown:'down',designEditText:'text',designFinishText:'text',designDuplicate:'copy',designDelete:'trash'}[id];artDecorate($(id),icon,['layerUp','layerDown','designDuplicate','designDelete'].includes(id)?null:$(id).textContent.trim())}
const artProperties=document.createElement('div');artProperties.id='artProperties';artProperties.hidden=true;artProperties.tabIndex=0;artProperties.setAttribute('role','tabpanel');artProperties.setAttribute('aria-label','Thuộc tính thiết kế');layersPanel.append(artProperties);
function artSection(title,nodes){const section=document.createElement('section');section.className='artPropertySection';const heading=document.createElement('h3');heading.textContent=title;section.append(heading,...nodes);artProperties.append(section)}
artSection('Chữ & bố cục',[artFontGroup,artParagraph]);artProperties.firstElementChild.querySelector('h3').textContent='Chữ & bố cục';
artSection('Viền tem mây',[document.querySelector('.colorGroup')]);artSection('Trang & kích cỡ',[document.querySelector('.printGroup'),document.querySelector('.dimensionsGroup')]);
const extraActions=[...artQuick.children].filter(node=>node.tagName==='BUTTON'&&!['artPropertiesButton','toggleLayers','print','artExportButton','save'].includes(node.id)&&!node.hidden);if(extraActions.length)artSection('Nội dung mẫu',extraActions);
artRibbon.replaceChildren(artTextZone,artImageZone,artSelectionTools);labelToolsGroup.remove();
const artLayersHeading=layersPanel.querySelector('.layersHeading'),artPropsTab=document.createElement('button'),artLayersTab=document.createElement('button');
for(const [button,id,label]of [[artPropsTab,'artPropertiesTab','Thuộc tính'],[artLayersTab,'artLayersTab','Lớp']]){button.id=id;button.type='button';button.className='artPanelTab';button.textContent=label;button.setAttribute('role','tab');button.onclick=()=>artOpenPanel(button===artPropsTab?'properties':'layers');artLayersHeading.prepend(button)}
$('layersList').tabIndex=0;$('layersList').setAttribute('role','tabpanel');$('layersList').setAttribute('aria-label','Danh sách lớp');artPropsTab.setAttribute('aria-controls','artProperties');artLayersTab.setAttribute('aria-controls','layersList');artDecorate($('closeLayersPanel'),'close',null);artLayersHeading.setAttribute('role','tablist');artLayersHeading.setAttribute('aria-label','Bảng thiết kế');
let artPanel='layers';function artSelectPanel(panel){artPanel=panel;artProperties.hidden=panel!=='properties';$('layersList').hidden=panel!=='layers';layersPanel.querySelector('.layersHint').hidden=panel!=='layers';artPropsTab.setAttribute('aria-selected',String(panel==='properties'));artLayersTab.setAttribute('aria-selected',String(panel==='layers'));artPropButton.setAttribute('aria-expanded',String(panel==='properties'&&!document.body.classList.contains('layersCollapsed')))}
function artOpenPanel(panel){document.body.classList.remove('layersCollapsed');layersPanel.inert=false;toggleLayers.setAttribute('aria-expanded','true');artSelectPanel(panel);artEnter(panel==='properties'?artProperties:$('layersList'),'panel');zoom()}
const artToggleLayers=toggleLayers.onclick;toggleLayers.onclick=()=>{if(artPanel!=='layers'||document.body.classList.contains('layersCollapsed'))artOpenPanel('layers');else{artToggleLayers();layersPanel.inert=document.body.classList.contains('layersCollapsed')}};$('closeLayersPanel').onclick=()=>{document.body.classList.add('layersCollapsed');layersPanel.inert=true;toggleLayers.setAttribute('aria-expanded','false');artPropButton.setAttribute('aria-expanded','false');toggleLayers.focus()};artSelectPanel('layers');
function artSyncContext(){const graphic=selectedGraphic(),multiple=graphic?graphicSelection().length>1:selectedLabels().length>1;artTextZone.hidden=!!graphic;artImageZone.hidden=!graphic;artContextLabel.textContent=isDesign()?(designKind.value==='text'?'Chữ':'Trang'):'Tem mây';for(const id of ['groupGraphics','ungroupGraphics'])$(id).hidden=!multiple;artProperties.children[1].hidden=isDesign();artUndo.disabled=historyIndex<=0;artRedo.disabled=historyIndex>=history.length-1;artIdentity.querySelector('strong').textContent=currentTemplateName||'Thiết kế mới';}
const artZoom=zoom;zoom=function(...args){const value=artZoom(...args);artSyncContext();return value};const artRecord=recordHistory;recordHistory=function(...args){const value=artRecord(...args);artUndo.disabled=historyIndex<=0;artRedo.disabled=historyIndex>=history.length-1;return value};
/* One token-driven animation controller; no animation schedules data or navigation. */
const artAnimations=new WeakMap(),artReduced=matchMedia('(prefers-reduced-motion: reduce)');
function artEnter(node,kind='menu',translate=true){if(!node||!node.isConnected)return;artAnimations.get(node)?.cancel();if(artReduced.matches)return;const style=getComputedStyle(document.documentElement),duration=parseFloat(style.getPropertyValue('--motion-'+kind));if(!duration||!node.animate)return;const animation=node.animate([{opacity:0,transform:translate?'translateY(6px)':'none'},{opacity:1,transform:'none'}],{duration,easing:style.getPropertyValue('--motion-ease').trim()});artAnimations.set(node,animation)}
artReduced.addEventListener('change',()=>{if(artReduced.matches)document.getAnimations().forEach(animation=>animation.cancel())});
const artKicker=document.createElement('span');artKicker.className='artHomeKicker';artKicker.textContent='XƯỞNG THIẾT KẾ · MINH ĐIẾN';home.querySelector('.homeHero').prepend(artKicker);$('homeAddTemplate').querySelector('.homeThumb span').innerHTML=artIcon('plus');$('homeAddTemplate').querySelector('.homeThumb svg').style.cssText='width:42px;height:42px';
for(const [type,icon]of [['all','layers'],['cloud','cloud'],['normal','file']])home.querySelector('[data-home-type="'+type+'"] .homeTypeIcon').innerHTML=artIcon(icon);$('homeAddTheme').querySelector('.homeTypeIcon').innerHTML=artIcon('plus');
const artRenderThemes=renderHomeThemes;renderHomeThemes=function(...args){const result=artRenderThemes(...args);home.querySelectorAll('[data-home-theme] .homeTypeIcon').forEach(icon=>icon.innerHTML=artIcon('theme'));return result};renderHomeThemes();
const artCtxItem=ctxItem;ctxItem=function(label,icon,shortcut,action,disabled,extraClass){const button=artCtxItem(label,icon,shortcut,action,disabled,extraClass);const key=/xóa/i.test(label)?'trash':/chép|nhân bản/i.test(label)?'copy':/nhóm/i.test(label)?'group':/khóa/i.test(label)?'lock':/tải/i.test(label)?'export':/lớp/i.test(label)?'layers':/căn/i.test(label)?'align':'properties';button.querySelector('.ctxIcon').innerHTML=artIcon(key);return button};
let artHomeScroll=0,artHomeOrigin=null,artLastType=homeType;
const artEnterEditor=enterHomeEditor;enterHomeEditor=function(...args){artHomeScroll=home.scrollTop;artHomeOrigin=document.activeElement?.closest?.('.homeCardOpen,#homeAddTemplate');artEnterEditor(...args);artEnter(document.querySelector('.wordWorkspace'),'page',false);artEnter(artHeader,'page');artSyncContext()};
const artShowHome=showTemHome;showTemHome=async function(...args){artCloseExport();await artShowHome(...args);home.scrollTop=artHomeScroll;if(artHomeOrigin?.isConnected)artHomeOrigin.focus({preventScroll:true});artEnter(home,'page',false)};homeBack.onclick=showTemHome;
const artFilterHome=filterHome;filterHome=function(...args){const result=artFilterHome(...args);if(artLastType!==homeType){artLastType=homeType;artEnter($('homeGrid'),'menu',false);artEnter($('homeRecentGrid'),'menu',false)}return result};$('homeSearch').oninput=filterHome;
const artObserver=new MutationObserver(records=>{for(const record of records){const node=record.target;if(record.type==='attributes'&&((node.tagName==='DIALOG'&&node.open)||(node.hasAttribute('hidden')===false&&['labelContextMenu','caseMenu','artExportMenu'].includes(node.id))))artEnter(node,node.tagName==='DIALOG'?'panel':'menu');for(const child of record.addedNodes){if(child.nodeType===1&&child.classList.contains('fontPickerMenu'))artEnter(child)}}});artObserver.observe(document.body,{subtree:true,attributes:true,attributeFilter:['hidden','open'],childList:true});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!labelMenu.hidden){labelMenu.hidden=true;$('labelSurface').focus({preventScroll:true})}});
const artFavicon=document.createElement('link');artFavicon.rel='icon';artFavicon.href='data:image/svg+xml,'+encodeURIComponent(artMark.replace('class="artMark"','xmlns="http://www.w3.org/2000/svg"'));document.head.append(artFavicon);
if(matchMedia('(max-width:800px)').matches){document.body.classList.add('layersCollapsed');layersPanel.inert=true;toggleLayers.setAttribute('aria-expanded','false')}artSyncContext();

/* Redraw controls whose base handlers update their text dynamically. */
const artLayerRender=renderLayersPanel;renderLayersPanel=function(...args){const result=artLayerRender(...args);layersPanel.querySelectorAll('.layerLock').forEach(button=>{button.setAttribute('aria-label',button.title);artDecorate(button,'lock',null)});return result};
const artAspectSync=syncAspectLock;syncAspectLock=function(...args){const result=artAspectSync(...args);const button=$('aspectLock');button.setAttribute('aria-label',button.title);artDecorate(button,'lock',$('lockRatio').checked?'Đã khóa tỷ lệ':'Tỷ lệ tự do');return result};
const artGraphicSync=syncGraphicControls;syncGraphicControls=function(...args){const result=artGraphicSync(...args);quickImageLock.setAttribute('aria-label',quickImageLock.textContent);artDecorate(quickImageLock,'lock',quickImageLock.textContent);return result};
$('sizeUp').innerHTML='A<span class="sup">+</span>';syncAspectLock();syncGraphicControls();renderLayersPanel();

artProperties.setAttribute('role','tabpanel');artProperties.setAttribute('aria-labelledby','artPropertiesTab');$('layersList').setAttribute('role','tabpanel');$('layersList').setAttribute('aria-labelledby','artLayersTab');
artLayersHeading.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)||![artPropsTab,artLayersTab].includes(document.activeElement))return;event.preventDefault();const target=event.key==='Home'?artLayersTab:event.key==='End'?artPropsTab:document.activeElement===artLayersTab?artPropsTab:artLayersTab;target.click();target.focus()});
$('zoomIn').textContent='+';$('zoomOut').textContent='−';

