'use strict';

/* Move the existing live controls rather than duplicate state or listeners. */
const topPropertyTools=document.createElement('div');topPropertyTools.id='artPropertyTools';topPropertyTools.setAttribute('role','group');topPropertyTools.setAttribute('aria-label','Công cụ thiết kế');artRibbon.prepend(topPropertyTools);
document.body.append(artProperties);artProperties.setAttribute('role','region');artProperties.removeAttribute('aria-labelledby');artProperties.setAttribute('aria-label','Công cụ thiết kế phía trên');
artPropsTab.remove();artLayersHeading.removeAttribute('role');artLayersHeading.removeAttribute('aria-label');$('layersList').removeAttribute('aria-labelledby');$('layersList').setAttribute('role','region');
const topPropertySections=[...artProperties.children],topPropertyButtons=[];
const topPropertyHeading=document.createElement('div');topPropertyHeading.className='topPropertyHeading';const topPropertyTitle=document.createElement('h2');const topPropertyClose=artButton('topPropertyClose','Đóng công cụ','close',()=>closeTopProperties(true));topPropertyHeading.append(topPropertyTitle,topPropertyClose);artProperties.append(topPropertyHeading);
let topPropertyAnchor=null,topPropertyIndex=-1;
function closeTopProperties(focus=false){artProperties.hidden=true;topPropertyButtons.forEach(b=>b.setAttribute('aria-expanded','false'));if(focus&&topPropertyAnchor?.isConnected)topPropertyAnchor.focus({preventScroll:true});topPropertyIndex=-1;}
function positionTopProperties(){if(artProperties.hidden||!topPropertyAnchor)return;const r=topPropertyAnchor.getBoundingClientRect();const top=Math.min(r.bottom+6,Math.max(8,innerHeight-100));artProperties.style.maxHeight=Math.max(60,innerHeight-top-8)+'px';artProperties.style.left=Math.max(8,Math.min(innerWidth-artProperties.offsetWidth-8,r.left))+'px';artProperties.style.top=top+'px';}
function openTopProperties(index,anchor){if(!artProperties.hidden&&topPropertyIndex===index){closeTopProperties(true);return;}closeTopProperties();topPropertyIndex=index;topPropertyAnchor=anchor;topPropertySections.forEach((section,i)=>section.hidden=i!==index);topPropertyTitle.textContent=topPropertySections[index].querySelector('h3').textContent;artProperties.hidden=false;artProperties.scrollTop=0;anchor.setAttribute('aria-expanded','true');positionTopProperties();artEnter(artProperties,'menu');topPropertyClose.focus({preventScroll:true});}
for(const [index,section] of topPropertySections.entries()){const label=section.querySelector('h3').textContent;const icon=['properties','cloud','file','text','copy'][index]||'properties';const b=index===0?artPropButton:artButton('topProperty-'+index,label,icon,()=>{});b.onclick=()=>openTopProperties(index,b);b.title=label;b.setAttribute('aria-label',label);b.setAttribute('aria-controls','artProperties');b.setAttribute('aria-expanded','false');topPropertyButtons.push(b);topPropertyTools.append(b);}
// There is one right-hand panel: Layers. Properties no longer change its state.
artSelectPanel=function(){artPanel='layers';$('layersList').hidden=false;layersPanel.querySelector('.layersHint').hidden=false;artLayersTab.setAttribute('aria-selected','true');};
artOpenPanel=function(panel){if(panel==='properties'){openTopProperties(2,topPropertyButtons[2]);return;}document.body.classList.remove('layersCollapsed');layersPanel.inert=false;toggleLayers.setAttribute('aria-expanded','true');artSelectPanel();zoom();};
const topPropertyContext=artSyncContext;artSyncContext=function(...args){const r=topPropertyContext(...args);topPropertySections.forEach((section,i)=>section.hidden=artProperties.hidden||i!==topPropertyIndex);topPropertyButtons[1].hidden=isDesign();if(isDesign()&&topPropertyIndex===1)closeTopProperties();return r;};
artSelectPanel();
document.addEventListener('pointerdown',event=>{if(!artProperties.hidden&&!artProperties.contains(event.target)&&!topPropertyTools.contains(event.target)&&!event.target.closest('dialog,.fontPickerMenu'))closeTopProperties();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!artProperties.hidden&&!document.querySelector('dialog[open]')){event.preventDefault();closeTopProperties(true);}});
window.addEventListener('resize',positionTopProperties);artRibbon.addEventListener('scroll',positionTopProperties);topPropertyTools.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const items=topPropertyButtons.filter(b=>!b.hidden),index=items.indexOf(document.activeElement);if(index<0)return;event.preventDefault();items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowRight'?1:-1)+items.length)%items.length].focus();});
const topPropertyHome=showTemHome;showTemHome=async function(...args){closeTopProperties();return topPropertyHome(...args);};homeBack.onclick=showTemHome;
