const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn,execFileSync}=require('node:child_process');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'temhoa-image-')),profile=path.join(temp,'profile'),shots=process.env.TEMHOA_SCREENSHOTS||path.join(temp,'shots'),errors=[],failed=[];
 const server=spawn('python3',['-u','-c',"import mo_temhoa as m;from http.server import ThreadingHTTPServer;s=ThreadingHTTPServer(('127.0.0.1',0),m.Handler);print(s.server_address[1],flush=True);s.serve_forever()"],{env:{...process.env,TEMHOA_TEMPLATE_ROOT:path.join(temp,'templates')},stdio:['ignore','pipe','pipe']});
 const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(Number(d.toString().trim())));server.once('error',reject);});
 const options={headless:true,args:['--no-sandbox'],viewport:{width:1600,height:1000}};if(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH)options.executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
 let browser,p;
 const connect=async()=>{browser=await chromium.launchPersistentContext(profile,options);p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico')&&!r.url().includes('/api/background'))failed.push(r.url())});await p.goto('http://127.0.0.1:'+port);await p.waitForFunction(()=>window.TemImageTools);};
 const idle=()=>p.evaluate(()=>TemImageTools.idle);
 const shot=async name=>{fs.mkdirSync(shots,{recursive:true});await p.screenshot({path:path.join(shots,name+'.png'),animations:'disabled'});};
 const value=async(label,v)=>{await p.getByRole('spinbutton',{name:label+' — giá trị',exact:true}).fill(String(v));await p.getByRole('spinbutton',{name:label+' — giá trị',exact:true}).press('Tab');await idle();};
 const select=()=>p.evaluate(()=>{selectGraphicItems(decorations.find(x=>x.kind==='image'));syncGraphicControls();positionGraphicOverlays();});
 try{
 await connect();await p.getByRole('button',{name:'Thêm mẫu',exact:true}).click();
 const importedSource=await p.evaluate(()=>{const c=cv(2400,1600),x=c.getContext('2d');x.fillStyle='#b92c3b';x.fillRect(0,0,c.width,c.height);return c.toDataURL();});await p.locator('#graphicFile').setInputFiles({name:'anh-goc-2400x1600.png',mimeType:'image/png',buffer:Buffer.from(importedSource.split(',')[1],'base64')});await p.waitForFunction(()=>decorations.length===1);assert.equal(await p.evaluate(()=>graphicImages.get(decorations[0].src).width),2400);assert.equal(await p.evaluate(()=>graphicImages.get(decorations[0].src).height),1600);assert.equal(await p.evaluate(()=>decorations[0].src),importedSource);
 await select();const sliderResults=[];
 for(const [panel,label,key,min,max] of [['opacity','Độ mờ (%)','opacity',10,90],['edit','Làm mờ','blur',0,8],['edit','Nhiệt độ màu','temperature',0,30],['style','Độ nhòe bóng (px)','shadowBlur',0,25],['radius','Bo góc (%)','radius',0,25]]){
 await p.evaluate(()=>TemImageTools.idle);if(await p.locator('#image-close-panel').count())await p.locator('#image-close-panel').click();await p.evaluate(k=>TemImageTools.openPanel(k),panel);
 const result=await p.evaluate(async({label,key,min,max})=>{const n=[...document.querySelectorAll('input[type=range]')].find(n=>n.getAttribute('aria-label')===label);if(!n)throw Error(label);const old=preview;let previews=0;preview=async(...a)=>{previews++;return old(...a)};const before=history.length,revision=autoContext.revision;n.focus();for(let i=0;i<25;i++){n.value=min+(max-min)*i/24;n.dispatchEvent(new Event('input',{bubbles:true}));await TemImageTools.pending;}const during={previews,history:history.length-before,revision:autoContext.revision-revision,held:autoSuspended};n.dispatchEvent(new Event('change',{bubbles:true}));await TemImageTools.idle;const after=history.length-before;preview=old;return {label,during,after,value:selectedGraphic()[key]};},{label,key,min,max});assert.equal(result.during.previews,0);assert.equal(result.during.history,0);assert.equal(result.during.revision,0);assert.equal(result.during.held,1);assert.equal(result.after,1);sliderResults.push(result);
 }console.log('SLIDERS '+JSON.stringify(sliderResults));
 if(await p.locator('#image-close-panel').count())await p.locator('#image-close-panel').click();
 await p.evaluate(async()=>{await newDesignText('<div>Ban dau</div>');editDesignText();await flushAutoSave();});
 const typingBefore=await p.evaluate(()=>{window.stableLayerNodes=[...$('layersList').querySelectorAll('.layerRow')];return history.length});await p.locator('#temEditor').press('End');await p.locator('#temEditor').pressSequentially(' 50 ky tu thu nghiem hieu nang khi dang go chu',{delay:5});assert.equal(await p.evaluate(()=>history.length),typingBefore);await p.evaluate(()=>flushAutoSave());assert.equal(await p.evaluate(()=>history.length),typingBefore+1);assert.equal(await p.evaluate(()=>stableLayerNodes.every(n=>n.isConnected)),true);assert.equal(await p.evaluate(()=>autoContext.dirty),false);
 await p.locator('#artUndo').click();await p.waitForFunction(()=>!labelOperation);assert.equal(await p.evaluate(()=>editorText()),'Ban dau');await p.locator('#artRedo').click();await p.waitForFunction(()=>!labelOperation);assert.ok(await p.evaluate(()=>editorText().includes('hieu nang')));
 await p.evaluate(async()=>{const imageLabel=labels.find(l=>l.settings.decorations.some(i=>i.kind==='image'));await activateLabel(imageLabel.id);selectGraphicItems(decorations.find(i=>i.kind==='image'));syncGraphicControls();});
 const cdp=await browser.newCDPSession(p);const listenerCount=async()=>{const r=await cdp.send('Runtime.evaluate',{expression:'Object.fromEntries([document,window].map((n,i)=>[i,Object.values(getEventListeners(n)).reduce((a,v)=>a+v.length,0)]))',includeCommandLineAPI:true,returnByValue:true});return r.result.value;};const beforeListeners=await listenerCount();
 const stress=await p.evaluate(async()=>{const source=decorations[0].src;for(let i=0;i<100;i++){recordHistory();decorations[0].x+=.5;await preview();recordHistory();renderLayersPanel();}for(let i=0;i<120;i++){TemImageTools.openPanel('style');TemImageTools.openPanel('style');await TemImageTools.idle;}await flushAutoSave();return {history:history.length,assets:historyAssets.size,encodedBytes:history.reduce((n,s)=>n+s.length*2,0),sourceBytes:source.length*2,held:autoSuspended};});assert.ok(stress.history<=80);assert.ok(stress.assets<=2);assert.equal(stress.held,0);assert.deepEqual(await listenerCount(),beforeListeners);console.log('STRESS '+JSON.stringify(stress));
 await p.evaluate(async()=>{for(let i=0;i<60;i++){const c=cv(8,8),x=c.getContext('2d');x.fillStyle='rgb('+i+',20,30)';x.fillRect(0,0,8,8);await loadGraphic(c.toDataURL());}});assert.ok(await p.evaluate(()=>graphicImages.size<=32));assert.ok(await p.evaluate(()=>decorations.every(i=>i.kind!=='image'||graphicImages.has(i.src))));
 for(const count of [20,50]){await p.evaluate(async count=>{const base=copyLabelData(currentLabel().settings),images=[];for(let i=0;i<count;i++){const c=cv(512,512),x=c.getContext('2d');x.fillStyle='rgb('+i+',30,40)';x.fillRect(0,0,512,512);images.push(safeGraphic({kind:'image',src:c.toDataURL(),x:100+i%10*10,y:100,width:30,height:30}));}const docs=Array.from({length:Math.ceil(count/10)},(_,i)=>({...base,text:'',richHTML:'<div></div>',designKind:'design',layerStack:'{}',decorations:images.slice(i*10,i*10+10)}));await restoreLabelDocument({...docs[0],labels:docs,activeLabel:0});recordHistory();await flushAutoSave();},count);assert.equal(await p.evaluate(()=>labels.reduce((n,l)=>n+l.settings.decorations.filter(i=>i.kind==='image').length,0)),count);assert.ok(await p.evaluate(()=>labels.every(l=>l.settings.decorations.every(i=>graphicImages.has(i.src)))));}
 const manyImageName=await p.evaluate(()=>currentTemplateName);await p.goto('http://127.0.0.1:'+port);await p.waitForFunction(n=>homeEntries.some(e=>e.fileName===n),manyImageName);await p.evaluate(async n=>openHomeEntry(homeEntries.find(e=>e.fileName===n)),manyImageName);assert.equal(await p.evaluate(()=>labels.reduce((n,l)=>n+l.settings.decorations.filter(i=>i.kind==='image').length,0)),50);console.log('PASS 20/50 images across real labels, save and reload');
 await p.goto('http://127.0.0.1:'+port+'/?debugPerformance=1');await p.waitForFunction(()=>TemPerformance);const idleBefore=await p.evaluate(()=>JSON.stringify(TemPerformance.values));await p.waitForTimeout(1500);assert.equal(await p.evaluate(()=>JSON.stringify(TemPerformance.values)),idleBefore);assert.equal(await p.locator('#performanceDebug').count(),1);await p.goto('http://127.0.0.1:'+port);await p.waitForFunction(()=>TemImageTools);assert.equal(await p.locator('#performanceDebug').count(),0);
 const soakMinutes=Number(process.env.TEMHOA_SOAK_MINUTES)||0;if(soakMinutes){await p.getByRole('button',{name:'Thêm mẫu',exact:true}).click();await p.evaluate(async()=>{await TemShapes.insert('shape-square');});const end=Date.now()+soakMinutes*60000;let rounds=0,lastLog=Date.now();while(Date.now()<end){await p.evaluate(async()=>{recordHistory();decorations[0].x+=.1;await preview();recordHistory();await flushAutoSave();});rounds++;if(Date.now()-lastLog>60000){console.log('SOAK '+JSON.stringify({minutes:soakMinutes,rounds,remainingSeconds:Math.ceil((end-Date.now())/1000)}));lastLog=Date.now();}await p.waitForTimeout(250);}console.log('SOAK PASS '+rounds+' transactions over '+soakMinutes+' real minutes');}
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS live sliders, typing transaction, bounded asset-interned history, repeated panel listener stability, idle counters and image cache; '+temp);
 }finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exit(1)});
