const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn,execFileSync}=require('node:child_process');
(async()=>{
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'temhoa-shapes-')),shots=process.env.TEMHOA_SCREENSHOTS||path.join(temp,'shots'),errors=[],failed=[],profile=path.join(temp,'profile');
const server=spawn('python3',['-u','-c',"import mo_temhoa as m;from http.server import ThreadingHTTPServer;s=ThreadingHTTPServer(('127.0.0.1',0),m.Handler);print(s.server_address[1],flush=True);s.serve_forever()"],{env:{...process.env,TEMHOA_TEMPLATE_ROOT:path.join(temp,'templates')},stdio:['ignore','pipe','pipe']});const port=await new Promise(resolve=>server.stdout.once('data',d=>resolve(Number(d.toString().trim()))));
let browser,p;const options={headless:true,args:['--no-sandbox'],viewport:{width:1440,height:900}};if(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH)options.executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
const connect=async()=>{browser=await chromium.launchPersistentContext(profile,options);p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))failed.push(r.url())});await p.goto('http://127.0.0.1:'+port);await p.waitForFunction(()=>window.TemShapes);};
const shot=async name=>{fs.mkdirSync(shots,{recursive:true});await p.screenshot({path:path.join(shots,name+'.png'),animations:'disabled'});};const idle=()=>p.evaluate(()=>TemShapes.idle);
try{await connect();await p.getByRole('button',{name:'Thêm mẫu',exact:true}).click();await p.locator('#insertGraphics').click();assert.equal(await p.locator('#insertGraphics').getAttribute('aria-label'),'Emoji');assert.ok(await p.locator('#iconGrid [data-icon]').count()>20);assert.equal(await p.locator('#shapePicker').isVisible(),false);await p.locator('#closeGraphics').click();await p.locator('#insertShapes').click();await p.locator('#graphicsDialog').waitFor({state:'hidden'});assert.equal(await p.locator('#graphicsDialog').isVisible(),false);const count=await p.locator('#shapeGrid button').count();assert.ok(count>=50);await shot('shapes-desktop');await p.locator('#shapeSearch').fill('tam giac');assert.equal(await p.locator('#shapeGrid button:visible').count(),3);await p.keyboard.press('Escape');await p.locator('#shapePicker').waitFor({state:'hidden'});await p.waitForFunction(()=>document.activeElement===document.getElementById('insertShapes'));assert.equal(await p.locator('#insertShapes').evaluate(n=>n===document.activeElement),true);
// Every built-in path produces real pixels without remote assets.
const catalog=await p.evaluate(()=>TemShapes.catalog);for(const shape of catalog){const pixels=await p.evaluate(kind=>{const item=safeGraphic({kind,x:60,y:60,width:100,height:100,color:'#22bb66',strokeColor:'#25262b',strokeWidth:4});const c=cv(120,120);drawGraphic(c.getContext('2d'),item);const d=c.getContext('2d').getImageData(0,0,120,120).data;let n=0;for(let i=3;i<d.length;i+=4)if(d[i])n++;return n;},shape.key);assert.ok(pixels>40,shape.name);}
await p.locator('#insertShapes').click();await p.getByRole('button',{name:'Hình vuông',exact:true}).click();await p.waitForFunction(()=>decorations.length===1);assert.equal(await p.locator('#shapeToolbar').isVisible(),true);assert.equal(await p.locator('#artImageZone').isVisible(),false);await p.locator('#artUndo').click();await p.waitForFunction(()=>!labelOperation&&decorations.length===0);await p.locator('#artRedo').click();await p.waitForFunction(()=>!labelOperation&&decorations.length===1);await p.locator('.layerRow[aria-label="Hình vuông"]').click();
// Native color pickers emit input while choosing, before change/blur.
await p.locator('#shapeFillColor').evaluate(n=>{n.focus();for(const color of ['#112233','#abcdef','#22bb66']){n.value=color;n.dispatchEvent(new Event('input',{bubbles:true}));}});await idle();assert.equal(await p.evaluate(()=>selectedGraphic().color),'#22bb66');
await p.locator('#shapeStrokeColor').evaluate(n=>{n.focus();n.value='#0066ff';n.dispatchEvent(new Event('input',{bubbles:true}));});await idle();assert.equal(await p.evaluate(()=>selectedGraphic().strokeColor),'#0066ff');assert.equal(await p.evaluate(()=>selectedGraphic().strokeWidth),2);await p.locator('#artUndo').click();await p.waitForFunction(()=>!labelOperation&&decorations[0].strokeWidth===0);await p.locator('#artRedo').click();await p.waitForFunction(()=>!labelOperation&&decorations[0].strokeWidth===2);await p.locator('.layerRow[aria-label="Hình vuông"]').click();
assert.ok(await p.evaluate(()=>{const g=selectedGraphic(),c=cv(120,120);drawGraphic(c.getContext('2d'),{...g,x:60,y:60,width:100,height:100,angle:0});const d=c.getContext('2d').getImageData(0,0,120,120).data;let fill=false,stroke=false;for(let i=0;i<d.length;i+=4){fill ||= d[i]===34&&d[i+1]===187&&d[i+2]===102;stroke ||= d[i]===0&&d[i+1]===102&&d[i+2]===255;}return fill&&stroke;}));
await p.locator('#shapeFillColor').fill('#22bb66');await p.locator('#shapeFillColor').dispatchEvent('change');await idle();await p.locator('#shapeStrokeWidth').fill('5');await p.locator('#shapeStrokeWidth').press('Tab');await idle();await p.locator('#shapeStrokeStyle').selectOption('dash');await idle();await p.locator('#shapeOpacity').fill('65');await p.locator('#shapeOpacity').press('Tab');await idle();assert.equal(await p.evaluate(()=>selectedGraphic().opacity),.65);assert.equal(await p.evaluate(()=>selectedGraphic().strokeWidth),5);await shot('shape-selected');
const overlay=await p.locator('.graphicOverlay').first().boundingBox();await p.mouse.move(overlay.x+overlay.width/2,overlay.y+overlay.height/2);await p.mouse.down();await p.mouse.move(overlay.x+overlay.width/2+35,overlay.y+overlay.height/2+20,{steps:5});await p.mouse.up();await p.waitForTimeout(150);await p.evaluate(async()=>{recordHistory();selectedGraphic().angle=25;await preview();recordHistory();});
const saved=await p.evaluate(()=>settings());await p.evaluate(async doc=>restoreLabelDocument(doc),saved);assert.equal(await p.evaluate(()=>decorations[0].kind),'shape-square');assert.equal(await p.evaluate(()=>decorations[0].strokeColor),'#0066ff');await p.evaluate(()=>{selectGraphicItems(decorations[0]);syncGraphicControls();});const original=await p.evaluate(()=>JSON.stringify(selectedGraphic()));await p.evaluate(async()=>{selectedGraphic().locked=true;await preview();syncGraphicControls();});assert.equal(await p.locator('#shapeOpacity').isDisabled(),true);await p.evaluate(()=>{$('shapeOpacity').value=10;$('shapeOpacity').dispatchEvent(new Event('change'));});await idle();assert.equal(await p.evaluate(()=>selectedGraphic().opacity),.65);await p.evaluate(async()=>{selectedGraphic().locked=false;await preview();syncGraphicControls();});assert.equal(await p.evaluate(()=>JSON.stringify(selectedGraphic())),original);
// Native objects can group, duplicate and undo without losing their shape identity.
await p.evaluate(async()=>{await TemShapes.insert('shape-circle');selectGraphicItems(decorations[0],true);await contextGroupSelection(false);await preview();});assert.ok(await p.evaluate(()=>decorations.length===2&&decorations.every(x=>x.groupId===decorations[0].groupId&&x.groupId)));await p.evaluate(async()=>{await contextGroupSelection(true);await preview();});assert.ok(await p.evaluate(()=>decorations.every(x=>!x.groupId)));await p.evaluate(async()=>{selectGraphicItems(decorations[0]);await contextDuplicateSelection();});assert.equal(await p.evaluate(()=>decorations.length),3);await p.locator('#artUndo').click();await p.waitForFunction(()=>!labelOperation&&decorations.length===2);
await p.evaluate(async()=>{selectGraphicItems(decorations[0]);$('shapeOpacity').value=100;$('shapeOpacity').dispatchEvent(new Event('change'));});await idle();assert.ok(await p.evaluate(()=>vectorSVG().includes('fill="#22bb66"')));
const png=await p.evaluate(async()=>{const bytes=(await exportPNG()).png;return Array.from(bytes);});const pngPath=path.join(temp,'shapes.png');fs.writeFileSync(pngPath,Buffer.from(png));execFileSync('python3',['-c',"from PIL import Image;import sys;im=Image.open(sys.argv[1]).convert('RGB');pixels=set(im.getdata());assert (34,187,102) in pixels;assert (0,102,255) in pixels",pngPath]);
const download=p.waitForEvent('download');await p.evaluate(async()=>{await TemStudio.openProduction();await TemStudio.exportPDF();});const pdf=await download,pdfPath=path.join(temp,'shapes.pdf');await pdf.saveAs(pdfPath);execFileSync('python3',['-c',"import fitz,sys;d=fitz.open(sys.argv[1]);p=d[0].get_pixmap(matrix=fitz.Matrix(.5,.5));s=p.samples;assert any(abs(s[i]-34)<12 and abs(s[i+1]-187)<12 and abs(s[i+2]-102)<12 for i in range(0,len(s)-2,p.n))",pdfPath]);await p.keyboard.press('Escape');
// Real gradient controls: fill linear, stroke radial, history and actual exports.
await p.locator('#shapeFillGradient').click();await p.locator('#shapeGradientMode').selectOption('linear');await idle();await p.locator('#shapeGradientColor2').fill('#0066ff');await p.locator('#shapeGradientColor2').dispatchEvent('input');await idle();await p.locator('#shapeGradientAngle').fill('30');await p.locator('#shapeGradientAngle').dispatchEvent('input');await idle();assert.equal(await p.evaluate(()=>selectedGraphic().shapeFillPaint.angle),30);await p.locator('#shapeGradientMode').selectOption('radial');await idle();assert.ok(await p.evaluate(()=>{const c=cv(120,120);drawGraphic(c.getContext('2d'),{...selectedGraphic(),x:60,y:60,width:100,height:100,angle:0,strokeWidth:0});const ctx=c.getContext('2d'),a=ctx.getImageData(60,60,1,1).data,b=ctx.getImageData(90,90,1,1).data;return a[1]>b[1]+25&&b[2]>a[2]+40;}));await p.locator('#shapeGradientMode').selectOption('linear');await idle();await shot('shape-gradient-fill');await p.keyboard.press('Escape');await p.locator('#shapeGradientDialog').waitFor({state:'hidden'});await p.waitForFunction(()=>document.activeElement===$('shapeFillGradient'));
await p.locator('#artUndo').click();await p.waitForFunction(()=>!labelOperation&&decorations[0].shapeFillPaint.type==='radial');await p.locator('#artRedo').click();await p.waitForFunction(()=>!labelOperation&&decorations[0].shapeFillPaint.angle===30);await p.locator('.layerRow[aria-label="Hình vuông"]').click();
await p.locator('#shapeStrokeGradient').click();await p.locator('#shapeGradientMode').selectOption('linear');await idle();assert.equal(await p.evaluate(()=>selectedGraphic().shapeStrokePaint.type),'linear');await p.locator('#shapeGradientMode').selectOption('radial');await idle();await p.locator('#shapeGradientColor1').fill('#ff0000');await p.locator('#shapeGradientColor1').dispatchEvent('input');await idle();await p.locator('#shapeGradientColor2').fill('#ffff00');await p.locator('#shapeGradientColor2').dispatchEvent('input');await idle();await shot('shape-gradient-stroke');assert.equal(await p.locator('#shapeGradientAngleRow').isVisible(),false);await p.keyboard.press('Escape');await p.locator('#shapeGradientDialog').waitFor({state:'hidden'});
await shot('shape-gradient-canvas');const paints=await p.evaluate(()=>{const g=selectedGraphic();return {fill:g.shapeFillPaint,stroke:g.shapeStrokePaint};});assert.deepEqual(paints.fill,{type:'linear',colors:['#22bb66','#0066ff'],angle:30});assert.equal(paints.stroke.type,'radial');
assert.ok(await p.evaluate(()=>{const c=cv(120,120),g=selectedGraphic();drawGraphic(c.getContext('2d'),{...g,x:60,y:60,width:100,height:100,angle:0,strokeWidth:0});const ctx=c.getContext('2d'),a=ctx.getImageData(40,80,1,1).data,b=ctx.getImageData(80,40,1,1).data;return Math.abs(a[2]-b[2])+Math.abs(a[1]-b[1])>30;}));
const svgPath=path.join(temp,'gradients.svg');fs.writeFileSync(svgPath,await p.evaluate(()=>vectorSVG()));execFileSync('python3',['-c',"import xml.etree.ElementTree as E,sys,re;r=E.parse(sys.argv[1]).getroot();ns={'s':'http://www.w3.org/2000/svg'};assert r.findall('.//s:linearGradient',ns);assert r.findall('.//s:radialGradient',ns);ids=[n.attrib['id'] for n in r.iter() if 'id' in n.attrib];assert len(ids)==len(set(ids));assert all(v[5:-1] in ids for n in r.iter() for v in n.attrib.values() if v.startswith('url('))",svgPath]);
const gradientPng=path.join(temp,'gradient.png');fs.writeFileSync(gradientPng,Buffer.from(await p.evaluate(async()=>Array.from((await exportPNG()).png))));execFileSync('python3',['-c',"from PIL import Image;import sys;p=Image.open(sys.argv[1]).convert('RGB').getdata();assert any(r<100 and g>100 and b<120 for r,g,b in p);assert any(r<100 and g<150 and b>160 for r,g,b in p)",gradientPng]);
const gradientDownload=p.waitForEvent('download');await p.evaluate(async()=>{await TemStudio.openProduction();await TemStudio.exportPDF();});const gradientPdf=path.join(temp,'gradient.pdf');await (await gradientDownload).saveAs(gradientPdf);execFileSync('python3',['-c',"import fitz,sys;d=fitz.open(sys.argv[1]);s=d[0].get_pixmap().samples;p=list(zip(s[0::3],s[1::3],s[2::3]));assert any(r<100 and g>100 and b<120 for r,g,b in p);assert any(r<100 and g<150 and b>160 for r,g,b in p)",gradientPdf]);await p.keyboard.press('Escape');
await p.evaluate(()=>flushAutoSave());const name=await p.evaluate(()=>currentTemplateName);await browser.close();browser=null;await connect();await p.locator('#homeGrid .homeCardOpen').filter({hasText:name}).click();assert.ok(await p.evaluate(()=>labels.some(l=>l.settings.decorations.some(g=>g.kind==='shape-square'&&g.color==='#22bb66'))));
assert.ok(await p.evaluate(()=>labels.some(l=>l.settings.decorations.some(g=>g.shapeFillPaint?.type==='linear'&&g.shapeFillPaint.angle===30&&g.shapeStrokePaint?.type==='radial'))));await p.locator('.layerRow[aria-label="Hình vuông"]').click();await p.evaluate(async()=>{selectedGraphic().locked=true;await preview();syncGraphicControls();});assert.equal(await p.locator('#shapeFillGradient').isDisabled(),true);await p.evaluate(async()=>{selectedGraphic().locked=false;await preview();syncGraphicControls();});await p.setViewportSize({width:390,height:760});await p.locator('#shapeFillGradient').click();await shot('shape-gradient-small');const gradientBox=await p.locator('#shapeGradientDialog').boundingBox();assert.ok(gradientBox.x>=0&&gradientBox.x+gradientBox.width<=390&&gradientBox.y>=0&&gradientBox.y+gradientBox.height<=760);await p.keyboard.press('Escape');await p.locator('#shapeGradientDialog').waitFor({state:'hidden'});await p.locator('#shapeFillColor').evaluate(n=>{n.value='#123456';n.dispatchEvent(new Event('input'));});await idle();assert.equal(await p.evaluate(()=>selectedGraphic().shapeFillPaint.type),'solid');assert.equal(await p.evaluate(()=>selectedGraphic().shapeStrokePaint.type),'radial');await p.locator('#artUndo').click();await p.waitForFunction(()=>!labelOperation&&decorations[0].shapeFillPaint.type==='linear');await p.locator('#insertShapes').click();await shot('shapes-small');const box=await p.locator('#shapePicker').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390&&box.y>=0&&box.y+box.height<=760);await p.keyboard.press('Escape');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS '+count+' vector shapes, emoji split, accent-free search, insert undo/redo, fill/stroke/opacity, drag, grouping, locks, solid/linear/radial fill and border, gradient undo/focus/locks, PNG/SVG/PDF pixels, autosave/reopen and small window; '+shots);
}finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exit(1)});
