const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
const equal=(a,b)=>assert.equal(require('node:crypto').createHash('sha256').update(a).digest('hex'),require('node:crypto').createHash('sha256').update(b).digest('hex'));
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'temhoa-studio-')),profile=path.join(temp,'profile'),shots=process.env.TEMHOA_SCREENSHOTS;let errors=[],failed=[];
 const server=spawn('python3',['-u','-c',"import mo_temhoa as m; from http.server import ThreadingHTTPServer; s=ThreadingHTTPServer(('127.0.0.1',0),m.Handler); print(s.server_address[1],flush=True); s.serve_forever()"],{env:{...process.env,TEMHOA_TEMPLATE_ROOT:path.join(temp,'templates')},stdio:['ignore','pipe','pipe']});
 const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(Number(d.toString().trim())));server.once('error',reject);server.stderr.on('data',d=>process.stderr.write(d))});
 const options={headless:true,args:['--no-sandbox'],viewport:{width:1440,height:1000}};if(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH)options.executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
 let browser;
 const connect=async()=>{browser=await chromium.launchPersistentContext(profile,options);const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))failed.push(r.url())});await p.goto('http://127.0.0.1:'+port);await p.waitForFunction(()=>window.TemStudio&&window.TemStudioObjects);return p;};
 const shot=async(p,name)=>{if(shots){fs.mkdirSync(shots,{recursive:true});await p.screenshot({path:path.join(shots,name+'.png'),animations:'disabled'})}};
 try{
 let p=await connect();await p.getByRole('button',{name:'Thêm mẫu',exact:true}).click();await p.locator('#studioResources').click();
 const fixture=fs.readFileSync('assets/temhoa-icon.png');await p.locator('#studioLibrary input[type=file]').setInputFiles([{name:'Hoa đỏ.png',mimeType:'image/png',buffer:fixture},{name:'Bản trùng.png',mimeType:'image/png',buffer:fixture},{name:'Hỏng.png',mimeType:'image/png',buffer:Buffer.from('broken')}]);
 await p.waitForFunction(()=>document.querySelector('#studioLibrary [role=status]').textContent.includes('Đã thêm 1 ảnh'));assert.equal(await p.evaluate(async()=> (await TemStudio.listEntries()).length),1);
 await p.getByRole('button',{name:'☆ Yêu thích',exact:true}).click();await p.getByRole('button',{name:'Sửa',exact:true}).click();await p.locator('#studioEntryName').fill('Hoa Hải Phòng');await p.locator('#studioEntryTags').fill('khai trương, sinh nhật');await p.getByRole('button',{name:'Lưu thông tin',exact:true}).click();await p.getByRole('searchbox',{name:'Tìm tài nguyên'}).fill('hai phong');await p.getByRole('button',{name:'Chèn Hoa Hải Phòng',exact:true}).waitFor();await shot(p,'studio-library');
 const original=await p.evaluate(async()=> (await TemStudio.listEntries())[0]);
 // Round-trip backup validation keeps image bytes; importing existing id never overwrites.
 const saved=await p.evaluate(async()=>{const entries=await TemStudio.listEntries();return await TemStudio.validateEntries({format:'temhoa-library',version:1,entries})});equal(saved[0].src,original.src);
 const download=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Xuất kho',exact:true}).click()]);await download[0].saveAs(path.join(temp,'library.json'));const backup=JSON.parse(fs.readFileSync(path.join(temp,'library.json')));backup.entries[0].name='Không ghi đè';fs.writeFileSync(path.join(temp,'import.json'),JSON.stringify(backup));
 const chooser=await Promise.all([p.waitForEvent('filechooser'),p.getByRole('button',{name:'Nhập kho',exact:true}).click()]);await chooser[0].setFiles(path.join(temp,'import.json'));await p.waitForFunction(()=>document.querySelector('#studioLibrary [role=status]').textContent.includes('giữ nguyên'));assert.equal(await p.evaluate(async()=> (await TemStudio.listEntries())[0].name),original.name);
 // Quota failures reject and leave old data intact.
 assert.equal(await p.evaluate(async()=>{const old=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('Quota','QuotaExceededError')};try{await TemStudio.saveEntry({id:'quota'});return false}catch{return true}finally{IDBObjectStore.prototype.put=old}}),true);
 await p.getByRole('button',{name:'Chèn Hoa Hải Phòng',exact:true}).click();await p.waitForFunction(()=>decorations.length===1);equal(await p.evaluate(()=>decorations[0].src),original.src);
 // Two crops and background processing preserve the ultimate original.
 await p.evaluate(async()=>{const item=decorations[0];selectGraphicItems(item);await updatePhotoPreview();photoCrop={x:.1,y:.1,width:.8,height:.8};await $('applyGraphicCrop').onclick();await updatePhotoPreview();photoCrop={x:.1,y:.1,width:.6,height:.6};await $('applyGraphicCrop').onclick();$('graphicWhite').checked=true;await $('graphicWhite').onchange();await preview();recordHistory();await flushAutoSave();});
 equal(await p.evaluate(()=>decorations[0].sourceOriginal),original.src);const cropped=await p.evaluate(()=>settings()),cropSrc=cropped.labels.flatMap(x=>x.decorations||[])[0].src;assert.notEqual(cropSrc,original.src);
 await browser.close();p=await connect();assert.equal(await p.evaluate(async()=> (await TemStudio.listEntries())[0].name),original.name);
 await p.waitForFunction(()=>homeEntries.some(x=>x.saved));await p.locator('#homeGrid .homeCardOpen').first().click();await p.waitForFunction(()=>home.hidden&&!homeBusy&&!labelOperation);await p.evaluate(()=>selectGraphicItems(decorations[0]));await p.evaluate(()=>$('studioRestoreImage').onclick());equal(await p.evaluate(()=>decorations[0].src),original.src);
 await p.evaluate(async()=>{restoreHistory(-1);});await p.waitForFunction(src=>!labelOperation&&decorations[0]?.src===src,cropSrc);await p.evaluate(()=>{restoreHistory(1)});await p.waitForFunction(src=>!labelOperation&&decorations[0]?.src===src,original.src);
 await p.evaluate(()=>selectGraphicItems(decorations[0]));await p.evaluate(async()=>{await contextToggleLock();await updatePhotoPreview();photoCrop={x:0,y:0,width:.5,height:.5};await $('applyGraphicCrop').onclick();});equal(await p.evaluate(()=>decorations[0].src),original.src);await p.evaluate(()=>contextToggleLock());
 // Mixed text/photo page group, transforms through real pointer handles.
 await p.locator('#designAddText').click();await p.locator('#temEditor').fill('Nhóm chữ và ảnh');await p.locator('#smartEditToggle').click();
 const photoId=await p.evaluate(()=>labels.find(x=>x.settings.decorations?.length).id);await p.locator('#layersList .layerRow[data-label-id="'+photoId+'"]').first().click({modifiers:['Shift']});await p.waitForFunction(()=>selectedLabels().length===2);assert.equal(await p.evaluate(()=>selectedLabels().length),2);await p.evaluate(()=>selectWholeLabel(currentLabel()));await p.locator('.otherLabel').first().click({modifiers:['Shift']});assert.equal(await p.evaluate(()=>selectedLabels().length),2);
 await p.locator('#smartGroupToggle').click();assert.ok(await p.evaluate(()=>selectedLabels().every(x=>labelGroupKey(x))));await shot(p,'studio-mixed-group');
 const before=await p.evaluate(()=>selectedLabels().map(x=>({...TemStudioObjects.geometry(x),angle:x.settings.labelAngle||0})));
 const drag=async(selector,dx,dy)=>{const b=await p.locator(selector).boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2+dx,b.y+b.height/2+dy,{steps:5});await p.mouse.up();await p.waitForFunction(()=>!labelGroupDrag);};
 await drag('#wholeGroupFrame [data-group-handle=move]',45,35);assert.ok(await p.evaluate(x=>TemStudioObjects.geometry(selectedLabels()[0]).x>x,before[0].x));
 await drag('#wholeGroupFrame [data-group-handle=se]',30,25);await drag('#wholeGroupFrame [data-group-handle=rotate]',50,45);assert.ok(await p.evaluate(()=>selectedLabels().every(x=>Math.abs(x.settings.labelAngle)>1)));assert.ok(await p.evaluate(()=>vectorSVG().includes('transform="rotate(')));await shot(p,'studio-mixed-rotated');
 await p.evaluate(async()=>{await preview();recordHistory();await flushAutoSave()});const transformed=await p.evaluate(()=>settings());await p.evaluate(async data=>restoreLabelDocument(data),transformed);assert.equal(await p.evaluate(()=>selectedLabels().length),2);
 await p.locator('.graphicOverlay').first().click({button:'right'});await p.getByRole('menuitem',{name:'Tạo bản sao',exact:true}).click();await p.waitForFunction(()=>labels.length===4);assert.equal(await p.evaluate(()=>labels.length),4);await p.evaluate(()=>contextDeleteSelection());assert.equal(await p.evaluate(()=>labels.length),2);
 await p.evaluate(()=>contextToggleLock());const locked=await p.evaluate(()=>JSON.stringify(settings()));await drag('#wholeGroupFrame [data-group-handle=move]',35,20);assert.equal(await p.evaluate(()=>JSON.stringify(settings())),locked);await p.evaluate(()=>contextToggleLock());
 console.log('PASS assets, crop, restart, mixed transforms and lock');await p.evaluate(async()=>{recordHistory();await flushAutoSave()});const groupName=await p.evaluate(()=>currentTemplateName);await browser.close();p=await connect();await p.waitForFunction(name=>homeEntries.some(x=>x.fileName===name),groupName);await p.locator('#homeGrid .homeCard').filter({has:p.locator('.homeCardOpen strong',{hasText:groupName})}).locator('.homeCardOpen').click();await p.waitForFunction(()=>home.hidden&&!homeBusy&&!labelOperation&&labels.every(x=>x.size));assert.equal(await p.evaluate(()=>selectedLabels().length),2);
 const geometryBefore=await p.evaluate(()=>labels.map(x=>({...TemStudioObjects.geometry(x),angle:x.settings.labelAngle,group:x.settings.labelGroup})));await p.locator('#smartGroupToggle').click();const geometryAfter=await p.evaluate(()=>labels.map(x=>({...TemStudioObjects.geometry(x),angle:x.settings.labelAngle})));assert.deepEqual(geometryAfter,geometryBefore.map(({group,...x})=>x));
 await p.evaluate(()=>restoreHistory(-1));await p.waitForFunction(()=>!labelOperation&&selectedLabels().length===2&&selectedLabels().every(x=>labelGroupKey(x)));await p.evaluate(()=>restoreHistory(1));await p.waitForFunction(()=>!labelOperation&&labels.every(x=>!labelGroupKey(x)));
 // All quick recipes share an actual render preview. Long input stays within page.
 await p.evaluate(async()=>{await TemStudio.openLibrary('template')});await p.getByRole('button',{name:'Dùng mẫu Khai trương hồng phát',exact:true}).click();await p.locator('#studioField-recipient').fill('Cửa hàng Minh Điến Hải Phòng cùng toàn thể gia đình và bạn bè thân thiết chúc mừng khai trương');await p.locator('#studioField-sender').fill('Người gửi — Gia đình Minh Điến');await p.waitForFunction(()=>document.querySelector('.studioTemplatePreview').src.startsWith('data:image/png'));await shot(p,'studio-template');
 await p.evaluate(()=>TemStudio.refreshQuickPreview());const preview=await p.evaluate(()=>TemStudio.studioThumbnail(TemStudio.quickDocument()));await p.locator('#studioUseTemplate').click();await p.waitForFunction(()=>!homeBusy&&home.hidden);assert.equal(await p.evaluate(()=>isDesign()),true);equal(await p.evaluate(()=>TemStudio.studioThumbnail(settings())),preview);await p.evaluate(()=>restoreHistory(-1));await p.waitForFunction(()=>!labelOperation);assert.ok(await p.evaluate(()=>labels.some(x=>x.settings.text.includes('Nhóm chữ'))));await p.evaluate(()=>restoreHistory(1));await p.waitForFunction(()=>!labelOperation);equal(await p.evaluate(()=>TemStudio.studioThumbnail(settings())),preview);
 for(const recipe of await p.evaluate(()=>TemStudio.recipes))assert.equal(await p.evaluate(r=>{const d=TemStudio.recipeDocument(r,{heading:r.heading,recipient:'Người nhận',wish:r.wish,sender:'Người gửi'});return d.labels.every(x=>x.labelY>=0&&x.labelY+TemStudio.studioMeasure(x).height*x.labelScaleY<=previewPage().height)},recipe),true);
 // Save custom template with images and rich formatting, edits preview without changing source.
 await p.evaluate(async()=>{await TemStudio.openLibrary();await TemStudio.insertAsset((await TemStudio.listEntries()).find(x=>x.type==='image'));await TemStudio.openLibrary();});await p.getByRole('button',{name:'Lưu thiết kế thành mẫu',exact:true}).click();await p.locator('#studioTemplateName').fill('Mẫu cá nhân có ảnh');await p.getByRole('button',{name:'Lưu vào kho mẫu',exact:true}).click();await p.getByRole('button',{name:'Dùng mẫu Mẫu cá nhân có ảnh',exact:true}).click();await p.locator('#studioQuickTemplate input').first().fill('Nội dung thay mới');await p.locator('#studioUseTemplate').click();await p.waitForFunction(()=>home.hidden);assert.equal(await p.evaluate(()=>isDesign()),true);assert.ok(await p.evaluate(()=>labels.some(x=>x.settings.decorations?.length)));assert.ok(await p.evaluate(async()=> (await TemStudio.listEntries()).find(x=>x.type==='template').document.labels.some(x=>x.text.includes('CHÚC MỪNG'))));
 await p.evaluate(()=>TemStudio.openProduction(true));await p.locator('#studioLabelWidth').fill('70');await p.locator('#studioCopies').fill('50');await p.locator('#studioMarks').check();await p.locator('#studioPreviewPage').selectOption('1');assert.ok((await p.locator('.studioProductionForm').textContent()).includes('Trang 2'));await shot(p,'studio-production');
 const sourceBefore=await p.evaluate(()=>JSON.stringify(settings()));for(const paper of ['A5','A4','A3'])for(const orientation of ['portrait','landscape']){
 await p.locator('#studioPaper').selectOption(paper);await p.locator('#studioOrientation').selectOption(orientation);const expected=await p.evaluate(()=>TemStudio.printPlan());const d=await Promise.all([p.waitForEvent('download'),p.locator('#studioExportPDF').click()]);const target=path.join(temp,paper+'-'+orientation+'.pdf');await d[0].saveAs(target);fs.writeFileSync(target+'.json',JSON.stringify(expected));
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(settings())),sourceBefore);await p.locator('#studioPrintMode').selectOption('page');for(const paper of ['A5','A4','A3'])for(const orientation of ['portrait','landscape']){await p.locator('#studioPaper').selectOption(paper);await p.locator('#studioOrientation').selectOption(orientation);const expected=await p.evaluate(()=>TemStudio.printPlan());const d=await Promise.all([p.waitForEvent('download'),p.locator('#studioExportPDF').click()]);const target=path.join(temp,'Page-'+paper+'-'+orientation+'.pdf');await d[0].saveAs(target);fs.writeFileSync(target+'.json',JSON.stringify(expected));}assert.equal(await p.evaluate(()=>JSON.stringify(settings())),sourceBefore);
 await p.keyboard.press('Escape');await p.setViewportSize({width:390,height:760});await p.evaluate(()=>TemStudio.openLibrary());await shot(p,'studio-small');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.keyboard.press('Escape');await p.evaluate(async()=>{const img=await loadGraphic((await TemStudio.listEntries()).find(x=>x.type==='image').src),canvas=cv(200,200),ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,200,200);ctx.drawImage(img,0,0,200,200);const jpeg=canvas.toDataURL('image/jpeg');const entry=await TemStudio.assetFromFile(new File([TemStudioCore.dataBytes(jpeg)],'Ảnh JPG.jpg',{type:'image/jpeg'}));await TemStudio.insertAsset(entry);selectGraphicItems(decorations[0]);await $('openBackgroundAI').onclick();if(!aiTarget.original.startsWith('data:image/png;base64,'))throw Error('AI requires PNG');const image=await loadGraphic(aiTarget.original);aiDraw($('aiAfter'),image);$('aiAfter').getContext('2d').clearRect(0,0,10,10);aiResult=$('aiAfter').toDataURL('image/png');await $('aiApply').onclick();if(decorations[0].sourceOriginal!==jpeg)throw Error('AI lost JPEG original');await $('studioRestoreImage').onclick();if(decorations[0].src!==jpeg)throw Error('AI restore failed');});
 await p.evaluate(()=>TemStudio.openLibrary('ornament'));await p.locator('#studioLibrary .studioCard').first().getByRole('button',{name:'☆ Yêu thích',exact:true}).click();await p.getByRole('combobox',{name:'Loại tài nguyên',exact:true}).selectOption('favorite');await p.waitForFunction(()=>document.querySelectorAll('#studioLibrary .studioCard').length===2);assert.equal(await p.locator('#studioLibrary .studioCard').count(),2);await p.keyboard.press('Escape');
 await p.evaluate(()=>TemStudio.openLibrary('image'));p.once('dialog',d=>d.accept());await p.locator('#studioLibrary').getByRole('button',{name:'Xóa',exact:true}).click();await p.waitForFunction(async()=>!(await TemStudio.listEntries()).some(x=>x.type==='image'));assert.ok(await p.evaluate(()=>decorations.some(x=>x.src.startsWith('data:image/'))));await p.keyboard.press('Escape');
 await p.evaluate(async()=>{const imageId=activeLabelId;await newDesignText('<div>Chữ cùng ảnh và hình</div>');const textId=activeLabelId;await newDesignText('<div></div>');await addGraphic('star');saveActiveLabel();const shapeId=activeLabelId;selectedGraphicId=null;selectedGraphicSet.clear();selectedLabelSet=new Set([imageId,textId,shapeId]);await contextGroupSelection(false);if(selectedLabels().length!==3||!selectedLabels().every(x=>labelGroupKey(x)))throw Error('Mixed shape group failed');const data=settings();await restoreLabelDocument(data);if(selectedLabels().length!==3||!selectedLabels().some(x=>x.settings.decorations.some(g=>g.kind==='star')))throw Error('Mixed shape restore failed');await contextGroupSelection(true);});
 const denied=await browser.newPage();await denied.addInitScript(()=>{indexedDB.open=()=>{throw new DOMException('Denied','SecurityError')}});await denied.goto('http://127.0.0.1:'+port);await denied.waitForFunction(()=>window.TemStudio);assert.equal(await denied.evaluate(async()=>{try{await TemStudio.openLibrary();return false}catch{return !!document.querySelector('#studioLibrary [role=status]').textContent}}),true);await denied.close();
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('PASS studio flows; PDF fixtures: '+temp);fs.writeFileSync('/tmp/temhoa-studio-fixtures',temp);
 }finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exit(1)});
